version: "3"
services:
  dali-app:
    container_name: dali-app
    image: yszk0123/dali-app
    command: yarn db:migrate && yarn start
    env_file:
      - .env
      - app.env
    depends_on:
      - dali-database
    networks:
      dali-app-network:
      dali-proxy-network:

  dali-database:
    container_name: dali-database
    image: postgres:9-alpine
    env_file: .env
    ports:
      - 5432
    volumes:
      - volume-dali-database:/var/lib/postgresql/data:cached
    networks:
      dali-app-network:

volumes:
  volume-dali-database:

networks:
  dali-app-network:
  dali-proxy-network:
