// flow-typed signature: 95430423595020a2606560f166fe71aa
// flow-typed version: <<STUB>>/express-history-api-fallback_v^2.2.1/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-history-api-fallback'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-history-api-fallback' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-history-api-fallback/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-history-api-fallback/dist/index.js' {
  declare module.exports: $Exports<'express-history-api-fallback/dist/index'>;
}
