#!/bin/bash -e
FILE_PATH="$1"
DATABASE_NAME="dali"

[[ -z "$FILE_PATH" ]] && cat <<EOS >&2 && exit 1
$0 [FILE_PATH]
EOS

gunzip -c "$FILE_PATH" \
  | docker exec -it --user=postgres dali-database psql "$DATABASE_NAME"
