export const CLOSE_ADD_TASK_UNIT_MODAL = 'CLOSE_ADD_TASK_UNIT_MODAL';
export const CLOSE_LINK_PROJECT_UNIT_MODAL = 'CLOSE_LINK_PROJECT_UNIT_MODAL';
export const OPEN_ADD_TASK_UNIT_MODAL = 'OPEN_ADD_TASK_UNIT_MODAL';
export const OPEN_LINK_PROJECT_UNIT_MODAL = 'OPEN_LINK_PROJECT_UNIT_MODAL';
